### PR TITLE
Fixed strip of properties.

### PR DESCRIPTION
**Pull request by teologov**
Hi, this pull request is a part of https://github.com/balderdashy/waterline/issues/1080 issue.

### CODE REVIEW

**Comment by dmarcelino** [comment]
Thanks @teologov! From glancing the changes they look good.

Any chance of adding a couple of tests: a regression one showing this change doesn't break existing functionality and a failing test that only works after applying the change?

**Comment by teologov** [comment]
Good point, @dmarcelino. Okay, I will add a couple of tests. Thanks.

**Comment by teologov** [comment]
Hey @dmarcelino 
I found out, that strip of non-reserved didn't work properly, and properties weren't removed. 
I need to update my forked repo, to fix new tests.

**Comment by teologov** [comment]
Okay, I've fixed unit tests. But integration tests are failing now.

**Pull request closed without merging**
