### PR TITLE
This fixes #17 by throwing an error message.

### LINKED ISSUE #17: Incorrect 'via' should raise more helpful error.
I have two models (many-to-many):

**User.js**
```javascript
var User = {
  ...
  attributes: {
   projects: {
      collection: 'Project',
      via: 'user' // Notice that this should be 'users' not 'user'
    }
  },
 ...
}

module.exports = User;
```

**Project.js**
```javascript
// models/project.js
var Project = {
  ...
  attributes: {
   users: {
      collection: 'User',
      via: 'projects'
    }
  },
 ...
}

module.exports = Project;
```

```shell
$ sails lift

info: Starting app...


/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/utils.js:46
  return hop.call(obj, prop);
             ^
TypeError: Cannot convert null to object
    at hasOwnProperty (native)
    at exports.object.hasOwnProperty (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/utils.js:46:14)
    at JoinTables.parseAttribute (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/joinTables.js:145:26)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/joinTables.js:80:22
    at Array.forEach (native)
    at JoinTables.buildJoins (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/joinTables.js:79:24)
    at new JoinTables (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/joinTables.js:40:23)
    at new module.exports (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema.js:33:17)
    at Waterline.initialize (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:106:17)
    at buildORM (/usr/local/lib/node_modules/sails/lib/hooks/orm/build-orm.js:48:15)
```

I would expect this to provide me with an error message telling me that Project does not reference an attribute key 'user' while attempting to map User.attributes.projects via Project.attributes.user, or something along those lines.

### PR DESCRIPTION
**Pull request by yagoferrer**
- fixes #17

### CODE REVIEW

**Comment by devinivy** [comment]
Looks good to me!  @mikermcneil mind taking a quick peek to thumbs this up/down?

**Comment by RWOverdijk** [comment]
@tjwebb bump.

**Comment by dmarcelino** [comment]
The integration tests passed: https://travis-ci.org/balderdashy/waterline-schema/jobs/45286882#L1817.

For references, this fixes #17.

**Comment by dmarcelino** [comment]
Thanks @yagoferrer!

**Pull request merged**
