### PR TITLE
Add support for dbType

### PR DESCRIPTION
**Pull request by dmarcelino**
As part of PR balderdashy/waterline#981 add `dbType` to the list of reservedWords.

### CODE REVIEW

**Comment by devinivy** [comment]
PR's good!  Let's wait to merge until https://github.com/balderdashy/waterline/pull/981is accepted by @particlebanana / community / etc.  Nice!

**Comment by devinivy** [comment]
One other thought... should `pkFormat` support `dbType`s?

**Comment by dmarcelino** [comment]
Thanks @devinivy, that is a very interesting question that didn't cross my mind at all. I don't know what would happen *now* if someone would try to use it but it would definitely be something worth implementing.

**Comment by devinivy** [comment]
Currently it would fail.  The code change shouldn't be _awfully_ difficult though.  Relevant code is here: https://github.com/balderdashy/waterline-schema/blob/master/lib/waterline-schema/attributes.js#L178-L200

**Comment by dmarcelino** [comment]
It could also be an issue on cross-adapter associations, right?

**Comment by devinivy** [comment]
I don't think that would be an issue, but I'm unsure.  Are you imagining `find` with `populate` failing?

**Comment by dmarcelino** [comment]
Potentially... but not sure.

**Comment by devinivy** [comment]
I don't imagining there being any issue, but it's worth a good test!

**Pull request merged**
